//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_project/Input/MasterInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MasterInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MasterInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MasterInputs"",
    ""maps"": [
        {
            ""name"": ""MasterMap"",
            ""id"": ""36f1fa7d-2997-46df-b26f-0e7a26d606d2"",
            ""actions"": [
                {
                    ""name"": ""Red Walls"",
                    ""type"": ""Button"",
                    ""id"": ""0ea2470a-2b68-4420-be2f-f2f48226a8f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Blue Walls"",
                    ""type"": ""Button"",
                    ""id"": ""c16f70fb-604d-4b2b-8712-5343efc84774"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Yellow Walls"",
                    ""type"": ""Button"",
                    ""id"": ""2134fee6-eb75-4ad6-a9cf-748847ccd45e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""932fe7d2-ebb1-4d05-a70c-72f5be7c4c18"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Red Walls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13be1de9-18ed-4975-ab97-0408a210c495"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blue Walls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad47fc0d-cbb2-4c1e-aca0-05cc9eea13f7"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yellow Walls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MasterMap
        m_MasterMap = asset.FindActionMap("MasterMap", throwIfNotFound: true);
        m_MasterMap_RedWalls = m_MasterMap.FindAction("Red Walls", throwIfNotFound: true);
        m_MasterMap_BlueWalls = m_MasterMap.FindAction("Blue Walls", throwIfNotFound: true);
        m_MasterMap_YellowWalls = m_MasterMap.FindAction("Yellow Walls", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MasterMap
    private readonly InputActionMap m_MasterMap;
    private List<IMasterMapActions> m_MasterMapActionsCallbackInterfaces = new List<IMasterMapActions>();
    private readonly InputAction m_MasterMap_RedWalls;
    private readonly InputAction m_MasterMap_BlueWalls;
    private readonly InputAction m_MasterMap_YellowWalls;
    public struct MasterMapActions
    {
        private @MasterInputs m_Wrapper;
        public MasterMapActions(@MasterInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @RedWalls => m_Wrapper.m_MasterMap_RedWalls;
        public InputAction @BlueWalls => m_Wrapper.m_MasterMap_BlueWalls;
        public InputAction @YellowWalls => m_Wrapper.m_MasterMap_YellowWalls;
        public InputActionMap Get() { return m_Wrapper.m_MasterMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MasterMapActions set) { return set.Get(); }
        public void AddCallbacks(IMasterMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MasterMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MasterMapActionsCallbackInterfaces.Add(instance);
            @RedWalls.started += instance.OnRedWalls;
            @RedWalls.performed += instance.OnRedWalls;
            @RedWalls.canceled += instance.OnRedWalls;
            @BlueWalls.started += instance.OnBlueWalls;
            @BlueWalls.performed += instance.OnBlueWalls;
            @BlueWalls.canceled += instance.OnBlueWalls;
            @YellowWalls.started += instance.OnYellowWalls;
            @YellowWalls.performed += instance.OnYellowWalls;
            @YellowWalls.canceled += instance.OnYellowWalls;
        }

        private void UnregisterCallbacks(IMasterMapActions instance)
        {
            @RedWalls.started -= instance.OnRedWalls;
            @RedWalls.performed -= instance.OnRedWalls;
            @RedWalls.canceled -= instance.OnRedWalls;
            @BlueWalls.started -= instance.OnBlueWalls;
            @BlueWalls.performed -= instance.OnBlueWalls;
            @BlueWalls.canceled -= instance.OnBlueWalls;
            @YellowWalls.started -= instance.OnYellowWalls;
            @YellowWalls.performed -= instance.OnYellowWalls;
            @YellowWalls.canceled -= instance.OnYellowWalls;
        }

        public void RemoveCallbacks(IMasterMapActions instance)
        {
            if (m_Wrapper.m_MasterMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMasterMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MasterMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MasterMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MasterMapActions @MasterMap => new MasterMapActions(this);
    public interface IMasterMapActions
    {
        void OnRedWalls(InputAction.CallbackContext context);
        void OnBlueWalls(InputAction.CallbackContext context);
        void OnYellowWalls(InputAction.CallbackContext context);
    }
}
